### ISSUE TITLE
Crash when viewing matches

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/MOZAIC#233]
I don't know exactly what I did, but at some point the app crashes each time I try to start a match or click on the matches tab. I'm on the `development` branch.

The console shows these errors:
```
Uncaught TypeError: Cannot read property 'config' of undefined
    at getBotData (http://localhost:3000/dist/bundle.js:17427:18)
    at http://localhost:3000/dist/bundle.js:17418:95
    at Array.map (native)
    at getMatchData (http://localhost:3000/dist/bundle.js:17418:65)
    at http://localhost:3000/dist/bundle.js:17391:16
    at Array.map (native)
    at Function.mapStateToProps [as mapToProps] (http://localhost:3000/dist/bundle.js:17390:46)
    at mapToPropsProxy (/home/procrat/repos/MOZAIC/planetwars/client/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:46)
    at Function.detectFactoryAndVerify (/home/procrat/repos/MOZAIC/planetwars/client/node_modules/react-redux/lib/connect/wrapMapToProps.js:63:19)
    at mapToPropsProxy (/home/procrat/repos/MOZAIC/planetwars/client/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:46)
    at handleFirstCall (/home/procrat/repos/MOZAIC/planetwars/client/node_modules/react-redux/lib/connect/selectorFactory.js:37:18)
    at pureFinalPropsSelector (/home/procrat/repos/MOZAIC/planetwars/client/node_modules/react-redux/lib/connect/selectorFactory.js:85:81)
    at Object.runComponentSelector [as run] (/home/procrat/repos/MOZAIC/planetwars/client/node_modules/react-redux/lib/components/connectAdvanced.js:43:25)
    at ProxyComponent.initSelector (/home/procrat/repos/MOZAIC/planetwars/client/node_modules/react-redux/lib/components/connectAdvanced.js:195:23)
    at ProxyComponent.initSelector (http://localhost:3000/dist/bundle.js:12246:30)
    at new Connect (/home/procrat/repos/MOZAIC/planetwars/client/node_modules/react-redux/lib/components/connectAdvanced.js:136:15)
/home/procrat/repos/MOZAIC/planetwars/client/node_modules/react-dom/cjs/react-dom.development.js:9643

The above error occurred in the <Connect(MatchViewer)> component:
    in Connect(MatchViewer) (created by Route)
    in Route (created by Routes)
    in Switch (created by Routes)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Routes)
    in Routes (created by Root)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Root)
    in Provider (created by Root)
    in Root
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```

**Comment by Procrat** [comment]
I think I know what the problem is. I removed a bot, but the matches it played persisted, so when the UI tries to show those matches, it can't find those bots.

**Comment by iasoon** [comment]
Yes, most likely that is the issue. Did your PR fix it?

**Comment by Procrat** [comment]
Yes.

**Comment by wschella** [comment]
Well this solution is actually very effective for it's simpleness. I'm a fan.
